[package]
name = "pwdlib"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_zxcvbn"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "^0.23"
zxcvbn = "3.1.0"
